name: Test

on:
  push:
    branches:
      - main
    paths-ignore:
      - .editorconfig
      - .gitignore
      - README.md
      - LICENSE.md
  pull_request:
    branches:
      - main
    paths-ignore:
      - .editorconfig
      - .gitignore
      - README.md
      - LICENSE.md

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@master

      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: |
            ~/node_modules
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Build
        run: npm install && npm run build

      - name: Run tests
        run: npm test
